import { SentenceQuestion, BossQuestion } from './types';

export const DETECTIVE_QUESTIONS = [
  {
    id: 'd1',
    word: 'problema',
    isException: true,
    correctArticle: 'el',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Հունական ծագմամբ բառ է (-ma վերջավորությամբ) -> Արական',
      'Վերջանում է -a տառով -> Իգական',
      'Հատուկ բառ է, որը հոգնակիում դառնում է la',
    ],
    optionsReasonsRu: [
      'Слово греческого происхождения на -ma -> Мужской род',
      'Оканчивается на -a -> Женский род',
      'Особое слово, превращающееся во мн.ч. в la',
    ],
    correctReasonIndex: 0,
    hintHy: 'Ուշադրություն. -ma վերջավորությամբ հունական բառերը ԱՐԱԿԱՆ են!',
    hintRu: 'Внимание: греческие слова на -ma всегда МУЖСКОГО рода!',
  },
  {
    id: 'd2',
    word: 'mano',
    isException: true,
    correctArticle: 'la',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Վերջանում է -o տառով, բայց բացառություն է՝ ԻԳԱԿԱՆ է',
      'Վերջանում է -o տառով -> Արական',
      'Երկսեռ բառ է, կախված մարդուց',
    ],
    optionsReasonsRu: [
      'Оканчивается на -o, но это исключение — ЖЕНСКИЙ род',
      'Оканчивается на -o -> Мужской род',
      'Двуполое слово, зависит от человека',
    ],
    correctReasonIndex: 0,
    hintHy: 'Հիշիր՝ «la mano» (ձեռք) իգական է!',
    hintRu: 'Запомни: «la mano» (рука) — женского рода!',
  },
  {
    id: 'd3',
    word: 'ciudad',
    isException: false,
    correctArticle: 'la',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Վերջանում է -dad -> Կանոնավոր ԻԳԱԿԱՆ',
      'Վերջանում է -d -> Արական բացառություն',
      'Հունական ծագմամբ բառ է',
    ],
    optionsReasonsRu: [
      'Окончание -dad -> Правильный ЖЕНСКИЙ род',
      'Окончание -d -> Мужское исключение',
      'Слово греческого происхождения',
    ],
    correctReasonIndex: 0,
    hintHy: '-dad, -tad, -tud վերջավորությունները ՄԻՇՏ իգական են (la)!',
    hintRu: 'Окончания -dad, -tad, -tud ВСЕГДА женского рода (la)!',
  },
  {
    id: 'd4',
    word: 'mapa',
    isException: true,
    correctArticle: 'el',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Հունական ծագմամբ -pa -> ԱՐԱԿԱՆ (el mapa)',
      'Վերջանում է -a -> Իգական (la mapa)',
      'Բառը չունի սեռ',
    ],
    optionsReasonsRu: [
      'Греческое происхождение -pa -> МУЖСКОЙ род (el mapa)',
      'Окончание -a -> Женский род (la mapa)',
      'Слово не имеет рода',
    ],
    correctReasonIndex: 0,
    hintHy: '«el mapa» (քարտեզ) արական է!',
    hintRu: '«el mapa» (карта) — мужского рода!',
  },
  {
    id: 'd5',
    word: 'agua',
    isException: true,
    correctArticle: 'el',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Քերականորեն իգական է, բայց եզակիում ստանում է EL՝ բարեհնչյունության համար',
      'Սովորական արական բառ է',
      'Միշտ դրվում է la',
    ],
    optionsReasonsRu: [
      'Грамматически женский род, но в ед.ч. с артиклем EL для звучности',
      'Обычное мужское слово',
      'Всегда используется с la',
    ],
    correctReasonIndex: 0,
    hintHy: '«el agua» (ջուր) իգական է, բայց եզակիում ասում ենք EL, իսկ ածականը՝ fría (el agua fría)!',
    hintRu: '«el agua» женского рода, но в ед.ч. проносится с EL, а прилагательное женское (el agua fría)!',
  },
  {
    id: 'd6',
    word: 'foto',
    isException: true,
    correctArticle: 'la',
    optionsArticles: ['el', 'la'],
    optionsReasonsHy: [
      'Կրճատված է «la fotografía» բառից, ուստի ԻԳԱԿԱՆ է',
      'Վերջանում է -o, ուստի արական է',
      'Կանոնավոր բառ է',
    ],
    optionsReasonsRu: [
      'Сокращение от «la fotografía», поэтому ЖЕНСКИЙ род',
      'Оканчивается на -o, поэтому мужской род',
      'Обычное регулярное слово',
    ],
    correctReasonIndex: 0,
    hintHy: 'Foto-ն la fotografía-ի կրճատումն է!',
    hintRu: 'Foto — это сокращение от la fotografía!',
  },
];

export const SENTENCE_QUESTIONS: SentenceQuestion[] = [
  {
    id: 's1',
    sentenceWithBlank: '___ problema es muy difícil de resolver.',
    correctArticle: 'El',
    options: ['El', 'La', 'Los', 'Las'],
    adjectiveQuestion: {
      sentenceWithBlank: 'El problema está ___ (resuelto / resuelta).',
      correctAdjective: 'resuelto',
      options: ['resuelto', 'resuelta'],
    },
    explanationHy: 'Problema-ն հունական ծագմամբ արական բառ է (el problema): Ածականը նույնպես դառնում է արական (resuelto):',
    explanationRu: 'Problema — мужского рода греческого происхождения (el problema). Прилагательное тоже мужское (resuelto).',
    fullSpanishSentence: 'El problema es muy difícil de resolver.',
    sentenceHy: 'Խնդիրը լուծելը շատ դժվար է:',
    sentenceRu: 'Проблему очень трудно решить.',
  },
  {
    id: 's2',
    sentenceWithBlank: '___ agua está muy ___ hoy.',
    correctArticle: 'El',
    options: ['El', 'La', 'Un', 'Una'],
    adjectiveQuestion: {
      sentenceWithBlank: 'El agua está ___ (fresco / fría).',
      correctAdjective: 'fría',
      options: ['fresco', 'fría'],
    },
    explanationHy: 'Ասում ենք «el agua» (հոդը el է), բայց ածականը մնում է իգական «fría», քանի որ բառը իգական է:',
    explanationRu: 'Говорим «el agua» (артикль el), но прилагательное остается женским «fría», так как слово женского рода.',
    fullSpanishSentence: 'El agua está muy fría hoy.',
    sentenceHy: 'Այսօր ջուրը շատ սառն է:',
    sentenceRu: 'Вода сегодня очень холодная.',
  },
  {
    id: 's3',
    sentenceWithBlank: '___ canción que escuchamos es hermosa.',
    correctArticle: 'La',
    options: ['El', 'La', 'Los', 'Las'],
    explanationHy: '-ción վերջավորությամբ բառերը ՄԻՇՏ իգական են (la canción):',
    explanationRu: 'Слова на -ción ВСЕГДА женского рода (la canción).',
    fullSpanishSentence: 'La canción que escuchamos es hermosa.',
    sentenceHy: 'Երգը, որը լսում ենք, գեղեցիկ է:',
    sentenceRu: 'Песня, которую мы слушаем, прекрасна.',
  },
  {
    id: 's4',
    sentenceWithBlank: '___ foto de la familia es nueva.',
    correctArticle: 'La',
    options: ['El', 'La', 'Un', 'Unos'],
    explanationHy: 'Foto-ն իգական է (la foto), քանի որ la fotografía-ի կրճատումն է:',
    explanationRu: 'Foto — женского рода (la foto), так как сокращение от la fotografía.',
    fullSpanishSentence: 'La foto de la familia es nueva.',
    sentenceHy: 'Ընտանիքի լուսանկարը նոր է:',
    sentenceRu: 'Семейное фото новое.',
  },
  {
    id: 's5',
    sentenceWithBlank: '___ mapa está sobre la mesa.',
    correctArticle: 'El',
    options: ['El', 'La', 'Las', 'Una'],
    explanationHy: 'Mapa-ն -pa վերջավորությամբ հունական բառ է -> ԱՐԱԿԱՆ (el mapa):',
    explanationRu: 'Mapa — греческое слово на -pa -> МУЖСКОЙ род (el mapa).',
    fullSpanishSentence: 'El mapa está sobre la mesa.',
    sentenceHy: 'Քարտեզը սեղանի վրա է:',
    sentenceRu: 'Карта лежит на столе.',
  },
  {
    id: 's6',
    sentenceWithBlank: '___ ciudad de Madrid es enorme.',
    correctArticle: 'La',
    options: ['El', 'La', 'Un', 'Los'],
    explanationHy: '-dad վերջավորությամբ բառերը ՄԻՇՏ իգական են (la ciudad):',
    explanationRu: 'Слова на -dad ВСЕГДА женского рода (la ciudad).',
    fullSpanishSentence: 'La ciudad de Madrid es enorme.',
    sentenceHy: 'Մադրիդ քաղաքը հսկայական է:',
    sentenceRu: 'Город Мадрид огромный.',
  },
];

export const BOSS_QUESTIONS: BossQuestion[] = [
  {
    id: 'bq1',
    questionSpanish: '¿Cuál es el artículo correcto para "sistema"?',
    questionHy: 'Ո՞րն է «sistema» բառի ճիշտ հոդը:',
    questionRu: 'Какой правильный артикль для «sistema»?',
    options: ['el sistema', 'la sistema', 'las sistema', 'los sistema'],
    correctIndex: 0,
    explanationHy: 'Sistema-ն հունական ծագմամբ -ma վերջավորությամբ արական բառ է (el sistema):',
    explanationRu: 'Sistema — мужского рода греческого происхождения на -ma (el sistema).',
    category: 'Բացառություններ (-ma)',
  },
  {
    id: 'bq2',
    questionSpanish: '¿Cómo se dice "սառը ջուր" en español?',
    questionHy: 'Ինչպե՞ս կլինի իսպաներեն «սառը ջուր» արտահայտությունը:',
    questionRu: 'Как сказать по-испански «холодная вода»?',
    options: ['el agua frío', 'la agua fría', 'el agua fría', 'la agua frío'],
    correctIndex: 2,
    explanationHy: 'Ճիշտ է «el agua fría». Եզակիում հոդը el է, իսկ ածականը՝ իգական fría!',
    explanationRu: 'Правильно «el agua fría». В ед.ч. артикль el, а прилагательное женское fría!',
    category: 'Հնչյունաբանություն (El agua)',
  },
  {
    id: 'bq3',
    questionSpanish: '¿Cuál de estas palabras es FEMENINA?',
    questionHy: 'Այս բառերից ո՞րն է ԻԳԱԿԱՆ:',
    questionRu: 'Какое из этих слов ЖЕНСКОГО рода?',
    options: ['el problema', 'el clima', 'la mano', 'el planeta'],
    correctIndex: 2,
    explanationHy: 'La mano (ձեռք) իգական է! Մյուսները հունական արական բառեր են (el problema, el clima, el planeta):',
    explanationRu: 'La mano (рука) — женского рода! Остальные — греческие слова мужского рода.',
    category: 'Իգական -o բացառություն',
  },
  {
    id: 'bq4',
    questionSpanish: '¿Qué sufijo garantiza que la palabra es FEMENINA?',
    questionHy: 'Ո՞ր վերջավորությունն է ԵՐԱՇԽԱՎՈՐՈՒՄ, որ բառը ԻԳԱԿԱՆ է:',
    questionRu: 'Какой суффикс ГАРАНТИРУЕТ, что слово ЖЕНСКОГО рода?',
    options: ['-aje', '-ción', '-or', '-ón'],
    correctIndex: 1,
    explanationHy: '-ción (օրինակ՝ la canción, la estación) ՄԻՇՏ իգական է:',
    explanationRu: '-ción (например, la canción, la estación) ВСЕГДА женского рода.',
    category: 'Վերջավորությունների կանոն',
  },
  {
    id: 'bq5',
    questionSpanish: '¿Cuál es el femenino de "el actor"?',
    questionHy: 'Ո՞րն է «el actor» բառի իգական ձևը:',
    questionRu: 'Какая форма женского рода для «el actor»?',
    options: ['la actora', 'la actriz', 'la actrice', 'la actora'],
    correctIndex: 1,
    explanationHy: 'El actor -> la actriz (դերասանուհի):',
    explanationRu: 'El actor -> la actriz (актриса).',
    category: 'Գոյականների զույգեր',
  },
  {
    id: 'bq6',
    questionSpanish: '¿Cuál es el plural de "el agua"?',
    questionHy: 'Ո՞րն է «el agua» բառի հոգնակի ձևը:',
    questionRu: 'Какая форма множественного числа у «el agua»?',
    options: ['los aguas', 'las aguas', 'los agua', 'las agua'],
    correctIndex: 1,
    explanationHy: 'Հոգնակիում վերադառնում է իգական հոդը՝ LAS AGUAS!',
    explanationRu: 'Во множественном числе возвращается женский артикль — LAS AGUAS!',
    category: 'Հոգնակի թիվ',
  },
  {
    id: 'bq7',
    questionSpanish: '¿Cómo se dice "կանացի լրագրող" (female journalist)?',
    questionHy: 'Ինչպե՞ս կլինի իսպաներեն «կին լրագրող» արտահայտությունը:',
    questionRu: 'Как сказать «женщина-журналист» по-испански?',
    options: ['la periodisto', 'la periodista', 'el periodista', 'la periodistina'],
    correctIndex: 1,
    explanationHy: '-ista վերջավորությունը չի փոխվում, փոխվում է հոդը՝ la periodista!',
    explanationRu: 'Окончание -ista не меняется, меняется только артикль — la periodista!',
    category: 'Երկսեռ բառեր',
  },
  {
    id: 'bq8',
    questionSpanish: '¿Qué palabra es MASCULINA a pesar de terminar en -a?',
    questionHy: 'Ո՞ր բառն է ԱՐԱԿԱՆ, չնայած ավարտվում է -a տառով:',
    questionRu: 'Какое слово МУЖСКОГО рода, хотя оканчивается на -a?',
    options: ['la casa', 'la mesa', 'el idioma', 'la luna'],
    correctIndex: 2,
    explanationHy: 'El idioma (լեզու) հունական արական բառ է!',
    explanationRu: 'El idioma (язык) — греческое слово мужского рода!',
    category: 'Հունական բառեր',
  },
];
