import { SpanishWord, WordPair } from './types';

export interface TheorySection {
  id: string;
  titleHy: string;
  titleRu: string;
  badge: string;
  summaryHy: string;
  summaryRu: string;
  rules: {
    ruleTitleHy: string;
    ruleTitleRu: string;
    explanationHy: string;
    explanationRu: string;
    examples: { spanish: string; article: 'el' | 'la'; translationHy: string; translationRu: string; note?: string }[];
  }[];
}

export const THEORY_SECTIONS: TheorySection[] = [
  {
    id: 'basic_rules',
    titleHy: '1. Հիմնական Կանոններ (-o / -a)',
    titleRu: '1. Основное правило (-o / -a)',
    badge: 'Հիմունքներ',
    summaryHy: 'Իսպաներենում գոյականների մեծ մասի սեռը որոշվում է վերջին տառով:',
    summaryRu: 'В испанском языке род большинства существительных определяется по последней букве.',
    rules: [
      {
        ruleTitleHy: 'Արական սեռ (Masculino) — Վերջանում է -o տառով',
        ruleTitleRu: 'Мужской род (Masculino) — Оканчивается на -o',
        explanationHy: '-o տառով ավարտվող գոյականները գրեթե 100% դեպքերում արական են և ստանում են «el» (եզակի) կամ «los» (հոգնակի) որոշյալ հոդը:',
        explanationRu: 'Слова, оканчивающиеся на -o, почти всегда мужского рода и употребляются с артиклем «el» (ед.ч.) или «los» (мн.ч.).',
        examples: [
          { spanish: 'libro', article: 'el', translationHy: 'գիրք', translationRu: 'книга' },
          { spanish: 'perro', article: 'el', translationHy: 'շուն', translationRu: 'собака' },
          { spanish: 'chico', article: 'el', translationHy: 'տղա', translationRu: 'мальчик' },
          { spanish: 'gato', article: 'el', translationHy: 'կատու', translationRu: 'кот' },
          { spanish: 'cuaderno', article: 'el', translationHy: 'տետր', translationRu: 'тетрадь' },
          { spanish: 'sol', article: 'el', translationHy: 'արև', translationRu: 'солнце' },
        ],
      },
      {
        ruleTitleHy: 'Իգական սեռ (Femenino) — Վերջանում է -a տառով',
        ruleTitleRu: 'Женский род (Femenino) — Оканчивается на -a',
        explanationHy: '-a տառով ավարտվող գոյականների մեծ մասը իգական են և ստանում են «la» (եզակի) կամ «las» (հոգնակի) որոշյալ հոդը:',
        explanationRu: 'Слова, оканчивающиеся на -a, как правило, женского рода и употребляются с артиклем «la» (ед.ч.) или «las» (мн.ч.).',
        examples: [
          { spanish: 'casa', article: 'la', translationHy: 'տուն', translationRu: 'дом' },
          { spanish: 'mesa', article: 'la', translationHy: 'սեղան', translationRu: 'стол' },
          { spanish: 'chica', article: 'la', translationHy: 'աղջիկ', translationRu: 'девочка' },
          { spanish: 'manzana', article: 'la', translationHy: 'խնձոր', translationRu: 'яблоко' },
          { spanish: 'puerta', article: 'la', translationHy: 'դուռ', translationRu: 'дверь' },
          { spanish: 'luna', article: 'la', translationHy: 'լուսին', translationRu: 'луна' },
        ],
      },
    ],
  },
  {
    id: 'suffix_rules',
    titleHy: '2. Վերջավորությունների Հատուկ Կանոններ',
    titleRu: '2. Правила по окончаниям и суффиксам',
    badge: 'Կանոնավոր',
    summaryHy: 'Որոշակի վերջավորություններ հստակ ցույց են տալիս բառի սեռը:',
    summaryRu: 'Определенные окончания четко указывают на род слова.',
    rules: [
      {
        ruleTitleHy: 'Իգական Վերջավորություններ (-ción, -sión, -dad, -tad, -tud, -z)',
        ruleTitleRu: 'Женские окончания (-ción, -sión, -dad, -tad, -tud, -z)',
        explanationHy: 'Բառերը, որոնք ավարտվում են այս վերջավորություններով, ՄԻՇՏ իգական են (la):',
        explanationRu: 'Слова с этими окончаниями ВСЕГДА женского рода (la):',
        examples: [
          { spanish: 'canción', article: 'la', translationHy: 'երգ', translationRu: 'песня', note: '-ción' },
          { spanish: 'estación', article: 'la', translationHy: 'կայարան', translationRu: 'станция', note: '-ción' },
          { spanish: 'televisión', article: 'la', translationHy: 'հեռուստատեսություն', translationRu: 'телевидение', note: '-sión' },
          { spanish: 'ciudad', article: 'la', translationHy: 'քաղաք', translationRu: 'город', note: '-dad' },
          { spanish: 'universidad', article: 'la', translationHy: 'համալսարան', translationRu: 'университет', note: '-dad' },
          { spanish: 'libertad', article: 'la', translationHy: 'ազատություն', translationRu: 'свобода', note: '-tad' },
          { spanish: 'actitud', article: 'la', translationHy: 'վերաբերմունք', translationRu: 'отношение', note: '-tud' },
          { spanish: 'luz', article: 'la', translationHy: 'լույս', translationRu: 'свет', note: '-z' },
          { spanish: 'paz', article: 'la', translationHy: 'խաղաղություն', translationRu: 'мир/покой', note: '-z' },
        ],
      },
      {
        ruleTitleHy: 'Արական Վերջավորություններ (-or, -ón, -án, -aje)',
        ruleTitleRu: 'Мужские окончания (-or, -ón, -án, -aje)',
        explanationHy: 'Այս վերջավորություններով ավարտվող բառերի մեծ մասը արական են (el):',
        explanationRu: 'Слова с такими окончаниями обычно мужского рода (el):',
        examples: [
          { spanish: 'amor', article: 'el', translationHy: 'սեր', translationRu: 'любовь', note: '-or' },
          { spanish: 'salón', article: 'el', translationHy: 'սրահ', translationRu: 'салон/зал', note: '-ón' },
          { spanish: 'avión', article: 'el', translationHy: 'ինքնաթիռ', translationRu: 'самолет', note: '-ón' },
          { spanish: 'pan', article: 'el', translationHy: 'հաց', translationRu: 'хлеб', note: '-án' },
          { spanish: 'viaje', article: 'el', translationHy: 'ճանապարհորդություն', translationRu: 'путешествие', note: '-aje' },
          { spanish: 'paisaje', article: 'el', translationHy: 'բնապատկեր', translationRu: 'пейзаж', note: '-aje' },
        ],
      },
    ],
  },
  {
    id: 'exceptions',
    titleHy: '3. Բացառություններ (Հունական բառեր և -o իգական)',
    titleRu: '3. Исключения (Греческие слова и -o женского рода)',
    badge: 'ՈՒՇԱԴՐՈՒԹՅՈՒՆ',
    summaryHy: 'Այս բառերը խաբուսիկ են. նրանք չեն ենթարկվում ստանդարտ -o/-a կանոնին:',
    summaryRu: 'Эти слова обманчивы: они не подчиняются стандартному правилу -o/-a.',
    rules: [
      {
        ruleTitleHy: 'Հունական ծագմամբ բառեր (-ma, -pa, -ta) — ԱՐԱԿԱՆ ԵՆ (EL)',
        ruleTitleRu: 'Слова греческого происхождения (-ma, -pa, -ta) — МУЖСКОГО РОДА (EL)',
        explanationHy: 'Չնայած ավարտվում են -a տառով, հունարենից փոխառյալ այս բառերը ԱՐԱԿԱՆ են և ստանում են «el» հոդը!',
        explanationRu: 'Несмотря на окончание -a, эти слова из греческого языка МУЖСКОГО рода и требуют артикль «el»!',
        examples: [
          { spanish: 'problema', article: 'el', translationHy: 'խնդիր', translationRu: 'проблема', note: 'el problema' },
          { spanish: 'tema', article: 'el', translationHy: 'թեմա', translationRu: 'тема', note: 'el tema' },
          { spanish: 'idioma', article: 'el', translationHy: 'լեզու', translationRu: 'язык', note: 'el idioma' },
          { spanish: 'sistema', article: 'el', translationHy: 'համակարգ', translationRu: 'система', note: 'el sistema' },
          { spanish: 'mapa', article: 'el', translationHy: 'քարտեզ', translationRu: 'карта', note: 'el mapa' },
          { spanish: 'planeta', article: 'el', translationHy: 'մոլորակ', translationRu: 'планета', note: 'el planeta' },
          { spanish: 'clima', article: 'el', translationHy: 'կլիմա', translationRu: 'климат', note: 'el clima' },
          { spanish: 'poema', article: 'el', translationHy: 'բանաստեղծություն', translationRu: 'стихотворение', note: 'el poema' },
        ],
      },
      {
        ruleTitleHy: 'Իգական բառեր -o վերջավորությամբ (LA)',
        ruleTitleRu: 'Женский род на -o (LA)',
        explanationHy: 'Վերջանում են -o տառով, բայց ԻԳԱԿԱՆ են:',
        explanationRu: 'Оканчиваются на -o, но являются ЖЕНСКОГО рода:',
        examples: [
          { spanish: 'mano', article: 'la', translationHy: 'ձեռք', translationRu: 'рука', note: 'la mano' },
          { spanish: 'foto', article: 'la', translationHy: 'լուսանկար', translationRu: 'фотография', note: 'կրճատ՝ la fotografía' },
          { spanish: 'moto', article: 'la', translationHy: 'մոտոցիկլետ', translationRu: 'мотоцикл', note: 'կրճատ՝ la motocicleta' },
          { spanish: 'radio', article: 'la', translationHy: 'ռադիո', translationRu: 'радио', note: 'la radio' },
        ],
      },
    ],
  },
  {
    id: 'special_cases',
    titleHy: '4. «El agua» կանոնը և Երկսեռ բառեր',
    titleRu: '4. Правило «El agua» и Двуполые слова',
    badge: 'Հատուկ',
    summaryHy: 'Հնչյունաբանական կանոններ և մասնագիտությունների/մարդկանց անուններ:',
    summaryRu: 'Фонетические правила и профессии/названия людей.',
    rules: [
      {
        ruleTitleHy: '«El agua» հնչյունական կանոնը',
        ruleTitleRu: 'Фонетическое правило «El agua»',
        explanationHy: 'Երբ ԻԳԱԿԱՆ գոյականը սկսվում է շեշտված «a» կամ «ha» հնչյունով, եզակի թվով դրվում է «el» հոդը (որպեսզի չլինի «la agua»): ԲԱՅՑ հոգնակիում դառնում է «las», իսկ ածականները մնում են իգական (el agua fría)!',
        explanationRu: 'Если ЖЕНСКОЕ существительное начинается на ударный звук «a» или «ha», в ед.ч. употребляется артикль «el» (во избежание слияния гласных «la agua»). Во мн.ч. возвращается «las», а прилагательные остаются женского рода!',
        examples: [
          { spanish: 'agua', article: 'el', translationHy: 'ջուր (el agua fría)', translationRu: 'вода (el agua fría)', note: 'Իգական է!' },
          { spanish: 'hacha', article: 'el', translationHy: 'կացին (las hachas)', translationRu: 'топор (las hachas)', note: 'Իգական է!' },
          { spanish: 'águila', article: 'el', translationHy: 'արծիվ (el águila real)', translationRu: 'орел (el águila real)', note: 'Իգական է!' },
        ],
      },
      {
        ruleTitleHy: 'Երկսեռ գոյականներ (el / la)',
        ruleTitleRu: 'Двуполые существительные (el / la)',
        explanationHy: 'Բառի վերջավորությունը չի փոխվում, փոխվում է միայն հոդը՝ կախված մարդու սեռից (-ista, -ante, -ente):',
        explanationRu: 'Окончание слова не меняется, меняется только артикль в зависимости от пола человека:',
        examples: [
          { spanish: 'estudiante', article: 'el', translationHy: 'ուսանող (տղա / աղջիկ)', translationRu: 'студент / студентка', note: 'el/la estudiante' },
          { spanish: 'artista', article: 'el', translationHy: 'նկարիչ / նկարչուհի', translationRu: 'художник / художница', note: 'el/la artista' },
          { spanish: 'periodista', article: 'el', translationHy: 'լրագրող (տղա / կին)', translationRu: 'журналист / журналистка', note: 'el/la periodista' },
          { spanish: 'cantante', article: 'el', translationHy: 'երգիչ / երգչուհի', translationRu: 'певец / певица', note: 'el/la cantante' },
        ],
      },
    ],
  },
];

export const ALL_DICTIONARY_WORDS: SpanishWord[] = [
  // Regular Masculine
  {
    id: 'w1',
    word: 'libro',
    gender: 'el',
    translationHy: 'գիրք',
    translationRu: 'книга',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -o տառով -> Արական (el libro)',
    ruleExplanationRu: 'Окончание -o -> Мужской род (el libro)',
    exampleSentence: 'El libro está en la mesa.',
    sentenceTranslationHy: 'Գիրքը սեղանին է:',
    sentenceTranslationRu: 'Книга лежит на столе.',
  },
  {
    id: 'w2',
    word: 'perro',
    gender: 'el',
    translationHy: 'շուն',
    translationRu: 'собака',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -o տառով -> Արական (el perro)',
    ruleExplanationRu: 'Окончание -o -> Мужской род (el perro)',
    exampleSentence: 'El perro corre en el jardín.',
    sentenceTranslationHy: 'Շունը վազում է այգում:',
    sentenceTranslationRu: 'Собака бегает в саду.',
  },
  {
    id: 'w3',
    word: 'sol',
    gender: 'el',
    translationHy: 'արև',
    translationRu: 'солнце',
    category: 'regular',
    ruleExplanationHy: 'Արական գոյական (el sol)',
    ruleExplanationRu: 'Существительное мужского рода (el sol)',
    exampleSentence: 'El sol brilla hoy.',
    sentenceTranslationHy: 'Այսօր արևը փայլում է:',
    sentenceTranslationRu: 'Сегодня светит солнце.',
  },
  {
    id: 'w4',
    word: 'cuaderno',
    gender: 'el',
    translationHy: 'տետր',
    translationRu: 'тетрадь',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -o տառով -> Արական (el cuaderno)',
    ruleExplanationRu: 'Окончание -o -> Мужской род (el cuaderno)',
    exampleSentence: 'Tengo el cuaderno azul.',
    sentenceTranslationHy: 'Ես ունեմ կապույտ տետրը:',
    sentenceTranslationRu: 'У меня синяя тетрадь.',
  },
  {
    id: 'w5',
    word: 'gato',
    gender: 'el',
    translationHy: 'կատու',
    translationRu: 'кот',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -o տառով -> Արական (el gato)',
    ruleExplanationRu: 'Окончание -o -> Мужской род (el gato)',
    exampleSentence: 'El gato duerme mucho.',
    sentenceTranslationHy: 'Կատուն շատ է քնում:',
    sentenceTranslationRu: 'Кот много спит.',
  },

  // Regular Feminine
  {
    id: 'w6',
    word: 'casa',
    gender: 'la',
    translationHy: 'տուն',
    translationRu: 'дом',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -a տառով -> Իգական (la casa)',
    ruleExplanationRu: 'Окончание -a -> Женский род (la casa)',
    exampleSentence: 'La casa es muy bonita.',
    sentenceTranslationHy: 'Տունը շատ գեղեցիկ է:',
    sentenceTranslationRu: 'Дом очень красивый.',
  },
  {
    id: 'w7',
    word: 'mesa',
    gender: 'la',
    translationHy: 'սեղան',
    translationRu: 'стол',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -a տառով -> Իգական (la mesa)',
    ruleExplanationRu: 'Окончание -a -> Женский род (la mesa)',
    exampleSentence: 'La mesa es de madera.',
    sentenceTranslationHy: 'Սեղանը փայտից է:',
    sentenceTranslationRu: 'Стол деревянный.',
  },
  {
    id: 'w8',
    word: 'puerta',
    gender: 'la',
    translationHy: 'դուռ',
    translationRu: 'дверь',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -a տառով -> Իգական (la puerta)',
    ruleExplanationRu: 'Окончание -a -> Женский род (la puerta)',
    exampleSentence: 'Abre la puerta, por favor.',
    sentenceTranslationHy: 'Բացիր դուռը, խնդրում եմ:',
    sentenceTranslationRu: 'Открой дверь, пожалуйста.',
  },
  {
    id: 'w9',
    word: 'manzana',
    gender: 'la',
    translationHy: 'խնձոր',
    translationRu: 'яблоко',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -a տառով -> Իգական (la manzana)',
    ruleExplanationRu: 'Окончание -a -> Женский род (la manzana)',
    exampleSentence: 'La manzana es dulce.',
    sentenceTranslationHy: 'Խնձորը քաղցր է:',
    sentenceTranslationRu: 'Яблоко сладкое.',
  },
  {
    id: 'w10',
    word: 'luna',
    gender: 'la',
    translationHy: 'լուսին',
    translationRu: 'луна',
    category: 'regular',
    ruleExplanationHy: 'Վերջանում է -a տառով -> Իգական (la luna)',
    ruleExplanationRu: 'Окончание -a -> Женский род (la luna)',
    exampleSentence: 'La luna es blanca.',
    sentenceTranslationHy: 'Լուսինը սպիտակ է:',
    sentenceTranslationRu: 'Луна белая.',
  },

  // Suffix rules Feminine
  {
    id: 'w11',
    word: 'canción',
    gender: 'la',
    translationHy: 'երգ',
    translationRu: 'песня',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -ción -> ՄԻՇՏ Իգական (la canción)',
    ruleExplanationRu: 'Окончание -ción -> ВСЕГДА Женский род (la canción)',
    exampleSentence: 'Me gusta esta canción.',
    sentenceTranslationHy: 'Ինձ դուր է գալիս այս երգը:',
    sentenceTranslationRu: 'Мне нравится эта песня.',
  },
  {
    id: 'w12',
    word: 'ciudad',
    gender: 'la',
    translationHy: 'քաղաք',
    translationRu: 'город',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -dad -> ՄԻՇՏ Իգական (la ciudad)',
    ruleExplanationRu: 'Окончание -dad -> ВСЕГДА Женский род (la ciudad)',
    exampleSentence: 'La ciudad es grande.',
    sentenceTranslationHy: 'Քաղաքը մեծ է:',
    sentenceTranslationRu: 'Город большой.',
  },
  {
    id: 'w13',
    word: 'universidad',
    gender: 'la',
    translationHy: 'համալսարան',
    translationRu: 'университет',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -dad -> ՄԻՇՏ Իգական (la universidad)',
    ruleExplanationRu: 'Окончание -dad -> ВСЕГДА Женский род (la universidad)',
    exampleSentence: 'Estudio en la universidad.',
    sentenceTranslationHy: 'Սովորում եմ համալսարանում:',
    sentenceTranslationRu: 'Я учусь в университете.',
  },
  {
    id: 'w14',
    word: 'libertad',
    gender: 'la',
    translationHy: 'ազատություն',
    translationRu: 'свобода',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -tad -> ՄԻՇՏ Իգական (la libertad)',
    ruleExplanationRu: 'Окончание -tad -> ВСЕГДА Женский род (la libertad)',
    exampleSentence: 'La libertad es importante.',
    sentenceTranslationHy: 'Ազատությունը կարևոր է:',
    sentenceTranslationRu: 'Свобода важна.',
  },
  {
    id: 'w15',
    word: 'luz',
    gender: 'la',
    translationHy: 'լույս',
    translationRu: 'свет',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -z -> Իգական (la luz)',
    ruleExplanationRu: 'Окончание -z -> Женский род (la luz)',
    exampleSentence: 'Enciende la luz.',
    sentenceTranslationHy: 'Միացրու լույսը:',
    sentenceTranslationRu: 'Включи свет.',
  },

  // Suffix rules Masculine
  {
    id: 'w16',
    word: 'amor',
    gender: 'el',
    translationHy: 'սեր',
    translationRu: 'любовь',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -or -> Արական (el amor)',
    ruleExplanationRu: 'Окончание -or -> Мужской род (el amor)',
    exampleSentence: 'El amor es fantástico.',
    sentenceTranslationHy: 'Սերը հրաշալի է:',
    sentenceTranslationRu: 'Любовь прекрасна.',
  },
  {
    id: 'w17',
    word: 'avión',
    gender: 'el',
    translationHy: 'ինքնաթիռ',
    translationRu: 'самолет',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -ón -> Արական (el avión)',
    ruleExplanationRu: 'Окончание -ón -> Мужской род (el avión)',
    exampleSentence: 'El avión vuela alto.',
    sentenceTranslationHy: 'Ինքնաթիռը բարձր է թռչում:',
    sentenceTranslationRu: 'Самолет летит высоко.',
  },
  {
    id: 'w18',
    word: 'viaje',
    gender: 'el',
    translationHy: 'ճանապարհորդություն',
    translationRu: 'путешествие',
    category: 'suffix_rule',
    ruleExplanationHy: 'Վերջանում է -aje -> Արական (el viaje)',
    ruleExplanationRu: 'Окончание -aje -> Мужской род (el viaje)',
    exampleSentence: 'Buen viaje a todos.',
    sentenceTranslationHy: 'Բարի ճանապարհորդություն բոլորին:',
    sentenceTranslationRu: 'Хорошего путешествия всем.',
  },

  // Greek Exceptions (-ma, -pa, -ta) -> EL
  {
    id: 'w19',
    word: 'problema',
    gender: 'el',
    translationHy: 'խնդիր',
    translationRu: 'проблема',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական ծագմամբ -ma -> ԱՐԱԿԱՆ (el problema)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое происхождение -ma -> МУЖСКОЙ род (el problema)',
    exampleSentence: 'No hay ningún problema.',
    sentenceTranslationHy: 'Ոչ մի խնդիր չկա:',
    sentenceTranslationRu: 'Нет никакой проблемы.',
  },
  {
    id: 'w20',
    word: 'tema',
    gender: 'el',
    translationHy: 'թեմա',
    translationRu: 'тема',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական -ma -> ԱՐԱԿԱՆ (el tema)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое -ma -> МУЖСКОЙ род (el tema)',
    exampleSentence: 'El tema es interesante.',
    sentenceTranslationHy: 'Թեման հետաքրքիր է:',
    sentenceTranslationRu: 'Тема интересная.',
  },
  {
    id: 'w21',
    word: 'idioma',
    gender: 'el',
    translationHy: 'լեզու',
    translationRu: 'язык',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական -ma -> ԱՐԱԿԱՆ (el idioma)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое -ma -> МУЖСКОЙ род (el idioma)',
    exampleSentence: 'El idioma español es bonito.',
    sentenceTranslationHy: 'Իսպաներեն լեզուն գեղեցիկ է:',
    sentenceTranslationRu: 'Испанский язык красив.',
  },
  {
    id: 'w22',
    word: 'sistema',
    gender: 'el',
    translationHy: 'համակարգ',
    translationRu: 'система',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական -ma -> ԱՐԱԿԱՆ (el sistema)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое -ma -> МУЖСКОЙ род (el sistema)',
    exampleSentence: 'El sistema funciona bien.',
    sentenceTranslationHy: 'Համակարգը լավ է աշխատում:',
    sentenceTranslationRu: 'Система работает хорошо.',
  },
  {
    id: 'w23',
    word: 'mapa',
    gender: 'el',
    translationHy: 'քարտեզ',
    translationRu: 'карта',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական -pa -> ԱՐԱԿԱՆ (el mapa)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое -pa -> МУЖСКОЙ род (el mapa)',
    exampleSentence: 'Miro el mapa del mundo.',
    sentenceTranslationHy: 'Նայում եմ աշխարհի քարտեզին:',
    sentenceTranslationRu: 'Я смотрю на карту мира.',
  },
  {
    id: 'w24',
    word: 'planeta',
    gender: 'el',
    translationHy: 'մոլորակ',
    translationRu: 'планета',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Հունական -ta -> ԱՐԱԿԱՆ (el planeta)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Греческое -ta -> МУЖСКОЙ род (el planeta)',
    exampleSentence: 'La Tierra es un planeta azul.',
    sentenceTranslationHy: 'Երկիրը կապույտ մոլորակ է:',
    sentenceTranslationRu: 'Земля - синяя планета.',
  },

  // Feminine Exceptions (-o) -> LA
  {
    id: 'w25',
    word: 'mano',
    gender: 'la',
    translationHy: 'ձեռք',
    translationRu: 'рука',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Վերջանում է -o, բայց ԻԳԱԿԱՆ է (la mano)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: На -o, но ЖЕНСКИЙ род (la mano)',
    exampleSentence: 'Tengo frío en la mano.',
    sentenceTranslationHy: 'Ձեռքս մսում է:',
    sentenceTranslationRu: 'У меня мерзнет рука.',
  },
  {
    id: 'w26',
    word: 'foto',
    gender: 'la',
    translationHy: 'լուսանկար',
    translationRu: 'фотография',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Կրճատ է la fotografía բառից -> ԻԳԱԿԱՆ (la foto)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Сокращение от la fotografía -> ЖЕНСКИЙ род (la foto)',
    exampleSentence: 'La foto es bonita.',
    sentenceTranslationHy: 'Լուսանկարը գեղեցիկ է:',
    sentenceTranslationRu: 'Фотография красивая.',
  },
  {
    id: 'w27',
    word: 'moto',
    gender: 'la',
    translationHy: 'մոտոցիկլետ',
    translationRu: 'мотоцикл',
    category: 'exception',
    ruleExplanationHy: 'ԲԱՑԱՌՈՒԹՅՈՒՆ. Կրճատ է la motocicleta բառից -> ԻԳԱԿԱՆ (la moto)',
    ruleExplanationRu: 'ИСКЛЮЧЕНИЕ: Сокращение от la motocicleta -> ЖЕНСКИЙ род (la moto)',
    exampleSentence: 'La moto va muy rápido.',
    sentenceTranslationHy: 'Մոտոցիկլետը շատ արագ է ընթանում:',
    sentenceTranslationRu: 'Мотоцикл едет очень быстро.',
  },

  // Special Phonetic -> EL AGUA
  {
    id: 'w28',
    word: 'agua',
    gender: 'la', // grammatically feminine!
    translationHy: 'ջուր (եզակիում` el agua)',
    translationRu: 'вода (в ед.ч. el agua)',
    category: 'special_phonetic',
    ruleExplanationHy: 'ՀԱՏՈՒԿ. Իգական է, բայց եզակիում դրվում է EL (el agua fría)!',
    ruleExplanationRu: 'ОСОБОЕ: Женского рода, но в ед.ч. с артиклем EL (el agua fría)!',
    exampleSentence: 'El agua está muy fría.',
    sentenceTranslationHy: 'Ջուրը շատ սառն է:',
    sentenceTranslationRu: 'Вода очень холодная.',
  },
];

export const WORD_PAIRS: WordPair[] = [
  {
    id: 'p1',
    masculine: 'el chico',
    masculineMeaningHy: 'տղա',
    masculineMeaningRu: 'мальчик',
    feminine: 'la chica',
    feminineMeaningHy: 'աղջիկ',
    feminineMeaningRu: 'девочка',
  },
  {
    id: 'p2',
    masculine: 'el rey',
    masculineMeaningHy: 'թագավոր',
    masculineMeaningRu: 'король',
    feminine: 'la reina',
    feminineMeaningHy: 'թագուհի',
    feminineMeaningRu: 'королева',
  },
  {
    id: 'p3',
    masculine: 'el actor',
    masculineMeaningHy: 'դերասան',
    masculineMeaningRu: 'актер',
    feminine: 'la actriz',
    feminineMeaningHy: 'դերասանուհի',
    feminineMeaningRu: 'актриса',
  },
  {
    id: 'p4',
    masculine: 'el doctor',
    masculineMeaningHy: 'բժիշկ',
    masculineMeaningRu: 'врач (мужчина)',
    feminine: 'la doctora',
    feminineMeaningHy: 'բժշկուհի',
    feminineMeaningRu: 'врач (женщина)',
  },
  {
    id: 'p5',
    masculine: 'el padre',
    masculineMeaningHy: 'հայր',
    masculineMeaningRu: 'отец',
    feminine: 'la madre',
    feminineMeaningHy: 'մայր',
    feminineMeaningRu: 'мать',
  },
  {
    id: 'p6',
    masculine: 'el gato',
    masculineMeaningHy: 'արու կատու',
    masculineMeaningRu: 'кот',
    feminine: 'la gata',
    feminineMeaningHy: 'էգ կատու',
    feminineMeaningRu: 'кошка',
  },
];
